before_script:
  - git submodule update --recursive --init SDF

test_ubuntu_gfortran:
  script:
    - export COMPILER=gfortran
    - ./run-tests-epoch.sh
  tags:
    - ubuntu
    - gfortran

test_ubuntu_intel:
  script:
    - export COMPILER=intel
    - ./run-tests-epoch.sh
  tags:
    - ubuntu
    - intel

test_osx:
  script:
    - export COMPILER=gfortran
    - ./run-tests-epoch.sh
  tags:
    - osx
