variables:
  GIT_STRATEGY: clone

before_script:
  - git submodule update --recursive --init SDF

test_ubuntu_gfortran:
  script:
    - COMPILER=gfortran scripts/run-tests-epoch-all.sh
  tags:
    - ubuntu
    - gfortran

test_ubuntu_intel:
  script:
    - COMPILER=intel scripts/run-tests-epoch-all.sh -b
  tags:
    - ubuntu
    - intel

test_osx:
  script:
    - COMPILER=gfortran scripts/run-tests-epoch-all.sh -b
  tags:
    - osx
