variables:
  GIT_STRATEGY: clone

before_script:
  - git submodule update --recursive --init SDF

test_ubuntu_gfortran:
  only:
    - branches@EPOCH/epoch
  script:
    - export COMPILER=gfortran
    - scripts/run-tests-epoch-all.sh
  tags:
    - ubuntu
    - gfortran

test_ubuntu_intel:
  only:
    - branches@EPOCH/epoch
  script:
    - export COMPILER=intel
    - scripts/run-tests-epoch-all.sh
  tags:
    - ubuntu
    - intel

test_osx:
  script:
    - export COMPILER=gfortran
    - scripts/run-tests-epoch-all.sh
  tags:
    - osx
