before_script:
  - git submodule update --recursive --init SDF

test_ubuntu_gfortran:
  script:
    - COMPILER=gfortran sh -x test_all.sh -et
    - sh -x test_all.sh -uv
  tags:
    - ubuntu
    - gfortran

test_ubuntu_intel:
  script:
    - COMPILER=intel sh -x test_all.sh -et
  tags:
    - ubuntu
    - intel

test_osx:
  script:
    - COMPILER=gfortran sh -x test_all.sh
  tags:
    - osx
