variables:
  GIT_STRATEGY: clone

before_script:
  - git submodule update --recursive --init SDF

test_ubuntu_gfortran:
  only:
    - branches@EPOCH/epoch
    - web
    - hook
  except:
    - master
    - wip/*
    - tag
  script:
    - COMPILER=gfortran scripts/run-tests-epoch-all.sh
  tags:
    - ubuntu
    - gfortran

test_ubuntu_intel:
  only:
    - branches@EPOCH/epoch
    - web
    - hook
  except:
    - master
    - wip/*
    - tag
  script:
    - COMPILER=intel scripts/run-tests-epoch-all.sh -b
  tags:
    - ubuntu
    - intel

test_ubuntu_pgi:
  only:
    - branches@EPOCH/epoch
    - web
    - hook
  except:
    - master
    - wip/*
    - tag
  script:
    - COMPILER=pgi MODE=debug scripts/run-tests-epoch-all.sh -b
  tags:
    - ubuntu
    - pgi

test_osx:
  only:
    - branches@EPOCH/epoch
    - web
    - hook
  except:
    - master
    - wip/*
    - tag
  script:
    - COMPILER=gfortran MODE=debug scripts/run-tests-epoch-all.sh -b
  tags:
    - osx
