before_script:
  - git submodule update --recursive --init SDF

test_ubuntu:
  script:
    - COMPILER=gfortran sh -x test_all.sh
  tags:
    - ubuntu

test_osx:
  script:
    - COMPILER=gfortran sh -x test_all.sh
  tags:
    - osx
