before_script:
  - git submodule update --recursive --init SDF

epoch1d_compilation:
  script:
    - cd epoch1d
    - make cleanall
    - make -j8 COMPILER=gfortran
    - cd ..

epoch2d_compilation:
  script:
    - cd epoch2d
    - make clean
    - make -j8 COMPILER=gfortran
    - cd ..

epoch3d_compilation:
  script:
    - cd epoch3d
    - make clean
    - make -j8 COMPILER=gfortran
    - cd ..

SDF_C_compilation:
  script:
    - cd SDF/C
    - make clean
    - make
    - cd ../..

SDF_utilities_compilation:
  script:
    - cd SDF/utilities
    - sh build -r
    - cd ../..
